/** Typed invoke wrappers over the generated v0 IPC bindings. */
export { EVENTS } from "../generated/ipc";
export {
  app_update_check,
  app_update_install,
  asset_list,
  asset_load,
  asset_store,
  clip_add,
  engine_play,
  engine_position,
  engine_record,
  engine_set_tempo,
  engine_stop,
  link_toggle,
  op_apply,
  op_redo,
  op_undo,
  param_set,
  project_get,
  project_new,
  project_open,
  project_save,
  track_add,
} from "../generated/ipc";
